# Generated by Django 2.1.7 on 2019-03-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='user_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='user_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='user_pwd',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
