# Generated by Django 2.1.7 on 2019-03-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(blank=True, max_length=128, null=True)),
                ('art_gallery', models.CharField(blank=True, max_length=128, null=True)),
                ('art_description', models.CharField(blank=True, max_length=256, null=True)),
                ('art_img', models.ImageField(blank=True, null=True, upload_to='art_image/')),
            ],
        ),
    ]
