# Generated by Django 2.1.7 on 2019-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artdata',
            name='art_author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
