# Generated by Django 2.1.7 on 2019-03-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_artdata_art_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artdata',
            name='art_gallery',
        ),
        migrations.AlterField(
            model_name='artdata',
            name='art_img',
            field=models.ImageField(blank=True, null=True, upload_to='media_cdn/'),
        ),
    ]
